apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: simplek8s-nl-tls
spec:
  secretName: simplek8s-nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: simplek8s.nl
  dnsNames:
    - simplek8s.nl
    - www.simplek8s.nl
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - simplek8s.nl
        - www.simplek8s.nl
